SET SERVEROUTPUT ON;



CREATE TABLE Usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    cpf VARCHAR2(14) UNIQUE NOT NULL,
    telefone VARCHAR2(20),
    email VARCHAR2(100)
);


CREATE TABLE Livros (
    id_livro NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(150) NOT NULL,
    autor VARCHAR2(100) NOT NULL,
    categoria VARCHAR2(50),
    quantidade_total NUMBER NOT NULL,
    quantidade_disponivel NUMBER NOT NULL
);


CREATE TABLE Emprestimos (
    id_emprestimo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    id_livro NUMBER NOT NULL,
    data_emprestimo DATE DEFAULT SYSDATE,
    prazo_dias NUMBER NOT NULL,
    data_prevista DATE NOT NULL,
    status_emprestimo VARCHAR2(20) DEFAULT 'EMPRESTADO',

    CONSTRAINT fk_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES Usuarios(id_usuario),

    CONSTRAINT fk_livro
        FOREIGN KEY (id_livro)
        REFERENCES Livros(id_livro)
);


CREATE TABLE Devolucoes (
    id_devolucao NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_emprestimo NUMBER NOT NULL,
    data_devolucao DATE DEFAULT SYSDATE,
    multa NUMBER(10,2),

    CONSTRAINT fk_emprestimo
        FOREIGN KEY (id_emprestimo)
        REFERENCES Emprestimos(id_emprestimo)
);




CREATE OR REPLACE PACKAGE pkg_biblioteca AS


    FUNCTION calcular_multa (
        p_id_emprestimo NUMBER
    )

    RETURN NUMBER;



    PROCEDURE cadastrar_usuario (
        p_nome VARCHAR2,
        p_cpf VARCHAR2,
        p_telefone VARCHAR2,
        p_email VARCHAR2
    );



    PROCEDURE consultar_usuarios;



    PROCEDURE cadastrar_livro (
        p_titulo VARCHAR2,
        p_autor VARCHAR2,
        p_categoria VARCHAR2,
        p_quantidade NUMBER
    );



    PROCEDURE consultar_livros;



    PROCEDURE atualizar_livro (
        p_id_livro NUMBER,
        p_titulo VARCHAR2,
        p_autor VARCHAR2,
        p_categoria VARCHAR2,
        p_quantidade NUMBER
    );



    PROCEDURE excluir_livro (
        p_id_livro NUMBER
    );



    PROCEDURE registrar_emprestimo (
        p_cpf VARCHAR2,
        p_id_livro NUMBER,
        p_prazo_dias NUMBER
    );



    PROCEDURE consultar_emprestimos;



    PROCEDURE registrar_devolucao (
        p_cpf VARCHAR2,
        p_id_emprestimo NUMBER
    );



    PROCEDURE consultar_devolucoes;

END pkg_biblioteca;
/


CREATE OR REPLACE PACKAGE BODY pkg_biblioteca AS


    FUNCTION calcular_multa (
        p_id_emprestimo NUMBER
    )

    RETURN NUMBER

    IS

        CURSOR c_emprestimo IS
            SELECT data_prevista
            FROM Emprestimos
            WHERE id_emprestimo = p_id_emprestimo;

        v_data_prevista DATE;

        v_dias_atraso NUMBER;

        v_multa NUMBER(10,2);

    BEGIN

        OPEN c_emprestimo;

        FETCH c_emprestimo
        INTO v_data_prevista;

        CLOSE c_emprestimo;


        -- VALIDAR EMPRESTIMO

        IF v_data_prevista IS NULL THEN

            RAISE_APPLICATION_ERROR(
                -20005,
                'Emprestimo nao encontrado.'
            );

        END IF;


        v_dias_atraso :=
            TRUNC(SYSDATE - v_data_prevista);


        IF v_dias_atraso > 0 THEN

            v_multa := v_dias_atraso * 2;

        ELSE

            v_multa := 0;

        END IF;


        RETURN v_multa;

    END calcular_multa;




    PROCEDURE cadastrar_usuario (
        p_nome VARCHAR2,
        p_cpf VARCHAR2,
        p_telefone VARCHAR2,
        p_email VARCHAR2
    )

    IS

    BEGIN

        -- VALIDAR CAMPOS OBRIGATORIOS

        IF p_nome IS NULL
        OR p_cpf IS NULL THEN

            RAISE_APPLICATION_ERROR(
                -20007,
                'Dados obrigatorios nao informados.'
            );

        END IF;


        INSERT INTO Usuarios (
            nome,
            cpf,
            telefone,
            email
        )

        VALUES (
            p_nome,
            p_cpf,
            p_telefone,
            p_email
        );

        DBMS_OUTPUT.PUT_LINE(
            'Usuario cadastrado.'
        );

    EXCEPTION

        -- CPF DUPLICADO

        WHEN DUP_VAL_ON_INDEX THEN

            RAISE_APPLICATION_ERROR(
                -20006,
                'CPF ja cadastrado.'
            );

    END cadastrar_usuario;



    PROCEDURE consultar_usuarios

    IS

        CURSOR c_usuarios IS
            SELECT *
            FROM Usuarios;

    BEGIN

        FOR usuario IN c_usuarios LOOP

            DBMS_OUTPUT.PUT_LINE(
                'ID: ' || usuario.id_usuario ||
                ' | Nome: ' || usuario.nome ||
                ' | CPF: ' || usuario.cpf ||
                ' | Telefone: ' || usuario.telefone ||
                ' | Email: ' || usuario.email
            );

        END LOOP;

    END consultar_usuarios;




    PROCEDURE cadastrar_livro (
        p_titulo VARCHAR2,
        p_autor VARCHAR2,
        p_categoria VARCHAR2,
        p_quantidade NUMBER
    )

    IS

    BEGIN

        -- Validar título obrigatório
        IF p_titulo IS NULL THEN

            RAISE_APPLICATION_ERROR(
                -20009,
                'Titulo obrigatorio.'
            );

        END IF;


        -- Validar autor obrigatório
        IF p_autor IS NULL THEN

            RAISE_APPLICATION_ERROR(
                -20010,
                'Autor obrigatorio.'
            );

        END IF;


        -- Validar quantidade maior que zero
        IF p_quantidade <= 0 THEN

            RAISE_APPLICATION_ERROR(
                -20008,
                'Quantidade deve ser maior que zero.'
            );

        END IF;


        INSERT INTO Livros (
            titulo,
            autor,
            categoria,
            quantidade_total,
            quantidade_disponivel
        )

        VALUES (
            p_titulo,
            p_autor,
            p_categoria,
            p_quantidade,
            p_quantidade
        );

        DBMS_OUTPUT.PUT_LINE(
            'Livro cadastrado.'
        );

    END cadastrar_livro;



    PROCEDURE consultar_livros

    IS

        CURSOR c_livros IS
            SELECT *
            FROM Livros;

    BEGIN

        FOR livro IN c_livros LOOP

            DBMS_OUTPUT.PUT_LINE(
                'ID: ' || livro.id_livro ||
                ' | Titulo: ' || livro.titulo ||
                ' | Autor: ' || livro.autor ||
                ' | Categoria: ' || livro.categoria ||
                ' | Quantidade: ' || livro.quantidade_total ||
                ' | Disponiveis: ' || livro.quantidade_disponivel
            );

        END LOOP;

    END consultar_livros;




    PROCEDURE atualizar_livro (
        p_id_livro NUMBER,
        p_titulo VARCHAR2,
        p_autor VARCHAR2,
        p_categoria VARCHAR2,
        p_quantidade NUMBER
    )

    IS

    BEGIN

        UPDATE Livros

        SET titulo = p_titulo,
            autor = p_autor,
            categoria = p_categoria,
            quantidade_total = p_quantidade

        WHERE id_livro = p_id_livro;


        -- Validar se o livro existe
        IF SQL%ROWCOUNT = 0 THEN

            RAISE_APPLICATION_ERROR(
                -20004,
                'Livro nao encontrado.'
            );

        END IF;


        DBMS_OUTPUT.PUT_LINE(
            'Livro atualizado.'
        );

    END atualizar_livro;



    PROCEDURE excluir_livro (
        p_id_livro NUMBER
    )

    IS

        v_titulo Livros.titulo%TYPE;

    BEGIN

        SELECT titulo
        INTO v_titulo
        FROM Livros
        WHERE id_livro = p_id_livro;

        DELETE FROM Devolucoes
        WHERE id_emprestimo IN (
            SELECT id_emprestimo
            FROM Emprestimos
            WHERE id_livro = p_id_livro
        );

        DELETE FROM Emprestimos
        WHERE id_livro = p_id_livro;

        DELETE FROM Livros
        WHERE id_livro = p_id_livro;

        DBMS_OUTPUT.PUT_LINE(
            'Livro removido: ' || v_titulo
        );

    EXCEPTION

        -- Livro não encontrado
        WHEN NO_DATA_FOUND THEN

            RAISE_APPLICATION_ERROR(
                -20004,
                'Livro nao encontrado.'
            );

    END excluir_livro;


    PROCEDURE registrar_emprestimo (
        p_cpf VARCHAR2,
        p_id_livro NUMBER,
        p_prazo_dias NUMBER
    )

    IS

        v_id_usuario NUMBER;

        v_data_prevista DATE;

        v_quantidade NUMBER;

    BEGIN

        -- VALIDAR CPF

        BEGIN

            SELECT id_usuario
            INTO v_id_usuario
            FROM Usuarios
            WHERE cpf = p_cpf;

        EXCEPTION

            WHEN NO_DATA_FOUND THEN

                RAISE_APPLICATION_ERROR(
                    -20003,
                    'CPF nao cadastrado.'
                );

        END;


        -- VALIDAR LIVRO

        BEGIN

            SELECT quantidade_disponivel
            INTO v_quantidade
            FROM Livros
            WHERE id_livro = p_id_livro;

        EXCEPTION

            WHEN NO_DATA_FOUND THEN

                RAISE_APPLICATION_ERROR(
                    -20004,
                    'Livro nao encontrado.'
                );

        END;


        -- VALIDAR ESTOQUE

        IF v_quantidade <= 0 THEN

            RAISE_APPLICATION_ERROR(
                -20002,
                'Livro indisponivel.'
            );

        END IF;


        -- VALIDAR PRAZO

        IF p_prazo_dias < 7
        OR p_prazo_dias > 30 THEN

            RAISE_APPLICATION_ERROR(
                -20001,
                'Prazo permitido e de 7 a 30 dias.'
            );

        END IF;


        -- CALCULAR DATA PREVISTA

        v_data_prevista :=
            SYSDATE + p_prazo_dias;


        -- REGISTRAR EMPRESTIMO

        INSERT INTO Emprestimos (
            id_usuario,
            id_livro,
            data_emprestimo,
            prazo_dias,
            data_prevista,
            status_emprestimo
        )

        VALUES (
            v_id_usuario,
            p_id_livro,
            SYSDATE,
            p_prazo_dias,
            v_data_prevista,
            'EMPRESTADO'
        );


        DBMS_OUTPUT.PUT_LINE(
            'Emprestimo realizado.'
        );


        DBMS_OUTPUT.PUT_LINE(
            'Data prevista: ' ||
            TO_CHAR(v_data_prevista, 'DD/MM/YYYY')
        );

    END registrar_emprestimo;




    PROCEDURE consultar_emprestimos

    IS

        CURSOR c_emprestimos IS
            SELECT *
            FROM Emprestimos;

    BEGIN

        FOR emprestimo IN c_emprestimos LOOP

            DBMS_OUTPUT.PUT_LINE(
                'ID Emprestimo: ' || emprestimo.id_emprestimo ||
                ' | Usuario: ' || emprestimo.id_usuario ||
                ' | Livro: ' || emprestimo.id_livro ||
                ' | Data Empréstimo: ' || emprestimo.data_emprestimo ||
                ' | Prazo Dias: ' || emprestimo.prazo_dias ||
                ' | Data Prevista: ' || emprestimo.data_prevista ||
                ' | Status: ' || emprestimo.status_emprestimo
            );

        END LOOP;

    END consultar_emprestimos;




    PROCEDURE registrar_devolucao (
        p_cpf VARCHAR2,
        p_id_emprestimo NUMBER
    )

    IS

        v_id_usuario NUMBER;

        v_multa NUMBER(10,2);

        v_status Emprestimos.status_emprestimo%TYPE;

    BEGIN

        -- VALIDAR CPF

        BEGIN

            SELECT id_usuario
            INTO v_id_usuario
            FROM Usuarios
            WHERE cpf = p_cpf;

        EXCEPTION

            WHEN NO_DATA_FOUND THEN

                RAISE_APPLICATION_ERROR(
                    -20003,
                    'CPF nao cadastrado.'
                );

        END;


        -- VALIDAR EMPRESTIMO

        BEGIN

            SELECT status_emprestimo
            INTO v_status
            FROM Emprestimos
            WHERE id_emprestimo = p_id_emprestimo;

        EXCEPTION

            WHEN NO_DATA_FOUND THEN

                RAISE_APPLICATION_ERROR(
                    -20005,
                    'Emprestimo nao encontrado.'
                );

        END;


        -- VALIDAR SE JA FOI DEVOLVIDO

        IF v_status = 'DEVOLVIDO' THEN

            RAISE_APPLICATION_ERROR(
                -20009,
                'Emprestimo ja devolvido.'
            );

        END IF;


        -- CALCULAR MULTA

        v_multa :=
            calcular_multa(
                p_id_emprestimo
            );


        -- REGISTRAR DEVOLUCAO

        INSERT INTO Devolucoes (
            id_emprestimo,
            data_devolucao,
            multa
        )

        VALUES (
            p_id_emprestimo,
            SYSDATE,
            v_multa
        );


        -- ATUALIZAR STATUS

        UPDATE Emprestimos

        SET status_emprestimo = 'DEVOLVIDO'

        WHERE id_emprestimo = p_id_emprestimo;


        DBMS_OUTPUT.PUT_LINE(
            'Devolucao realizada.'
        );


        DBMS_OUTPUT.PUT_LINE(
            'Multa: R$ ' || v_multa
        );

    END registrar_devolucao;



    PROCEDURE consultar_devolucoes

    IS

        CURSOR c_devolucoes IS
            SELECT *
            FROM Devolucoes;

    BEGIN

        FOR devolucao IN c_devolucoes LOOP

            DBMS_OUTPUT.PUT_LINE(
                'ID Devolucao: ' || devolucao.id_devolucao ||
                ' | Emprestimo: ' || devolucao.id_emprestimo ||
                ' | Multa: R$ ' || devolucao.multa
            );

        END LOOP;

    END consultar_devolucoes;


END pkg_biblioteca;
/

CREATE OR REPLACE TRIGGER trg_diminuir_livro

AFTER INSERT ON Emprestimos

FOR EACH ROW

BEGIN

    UPDATE Livros

    SET quantidade_disponivel =
        quantidade_disponivel - 1

    WHERE id_livro = :NEW.id_livro;

END;
/

CREATE OR REPLACE TRIGGER trg_aumentar_livro

AFTER INSERT ON Devolucoes

FOR EACH ROW

BEGIN

    UPDATE Livros

    SET quantidade_disponivel =
        quantidade_disponivel + 1

    WHERE id_livro = (

        SELECT id_livro

        FROM Emprestimos

        WHERE id_emprestimo =
            :NEW.id_emprestimo

    );

END;
/

--------------------------------------------------------
        -- T E S T E   D O  C Ó D I G O --
--------------------------------------------------------

-- CADASTRAR USUÁRIO
BEGIN

    pkg_biblioteca.cadastrar_usuario(
        'Eduardo Xavier',
        '12345678900',
        '81999999999',
        'eduardo@gmail.com'
    );

END;
/

-- CONSULTAR USUÁRIO
BEGIN

    pkg_biblioteca.consultar_usuarios;

END;
/

-- CADASTRAR LIVRO
BEGIN

    pkg_biblioteca.cadastrar_livro(
        'Dom Casmurro',
        'Machado de Assis',
        'Romance',
        10
    );

END;
/

-- CONSULTAR LIVRO
BEGIN

    pkg_biblioteca.consultar_livros;

END;
/

-- ATUALIZAR LIVRO
BEGIN

    pkg_biblioteca.atualizar_livro(
        1,
        'Dom Casmurro',
        'Machado de Assis',
        'Literatura Brasileira',
        15
    );

END;
/

-- LISTAR LIVROS
SELECT * FROM Livros;

-- REGISTRAR EMPRESTIMO
BEGIN

    pkg_biblioteca.registrar_emprestimo(
        '12345678900',
        1,
        15
    );

END;
/

-- LISTAR LIVROS
SELECT * FROM Livros;

-- CONSULTAR EMPRESTIMOS
BEGIN

    pkg_biblioteca.consultar_emprestimos;

END;
/

-- ATUALIZAR DATA_PREVISTA EMPRESTIMOS
UPDATE Emprestimos
SET data_prevista = SYSDATE - 5
WHERE id_emprestimo = 1;

-- REGISTRAR DEVOLUÇÃO
BEGIN

    pkg_biblioteca.registrar_devolucao(
        '12345678900',
        1
    );

END;
/

-- LISTAR DEVOLUÇÕES
SELECT * FROM Devolucoes;

-- LISTAR LIVROS
SELECT * FROM Livros;

-- CONSULTAR DEVOLUÇÕES
BEGIN

    pkg_biblioteca.consultar_devolucoes;

END;
/

-- EXCLUIR LIVRO
BEGIN

    pkg_biblioteca.excluir_livro(41);

END;
/

-- LISTAR LIVROS
SELECT * FROM Livros;


--------------------------------------------------------
        -- T E S T E S  D E  V A L I D A Ç Ã O --
--------------------------------------------------------

-- ERRO -20003
-- CPF NÃO CADASTRADO
BEGIN

    pkg_biblioteca.registrar_emprestimo(
        '99999999999',
        1,
        15
    );

END;
/


-- ERRO -20004
-- LIVRO NÃO ENCONTRADO
BEGIN

    pkg_biblioteca.registrar_emprestimo(
        '12345678900',
        999,
        15
    );

END;
/


-- ERRO -20001
-- PRAZO MENOR QUE 7 DIAS
BEGIN

    pkg_biblioteca.registrar_emprestimo(
        '12345678900',
        1,
        5
    );

END;
/


-- ERRO -20001
-- PRAZO MAIOR QUE 30 DIAS
BEGIN

    pkg_biblioteca.registrar_emprestimo(
        '12345678900',
        1,
        40
    );

END;
/


-- ERRO -20006
-- CPF JÁ CADASTRADO
BEGIN

    pkg_biblioteca.cadastrar_usuario(
        'Eduardo Xavier',
        '12345678900',
        '81999999999',
        'eduardo@gmail.com'
    );

END;
/


-- ERRO -20007
-- DADOS OBRIGATÓRIOS NÃO INFORMADOS
BEGIN

    pkg_biblioteca.cadastrar_usuario(
        NULL,
        '11111111111',
        '81999999999',
        'teste@gmail.com'
    );

END;
/


-- ERRO -20008
-- QUANTIDADE INVÁLIDA
BEGIN

    pkg_biblioteca.cadastrar_livro(
        'Livro Teste',
        'Autor Teste',
        'Categoria Teste',
        0
    );

END;
/


-- ERRO -20008
-- TÍTULO NÃO INFORMADO
BEGIN

    pkg_biblioteca.cadastrar_livro(
        NULL,
        'Autor Teste',
        'Categoria Teste',
        10
    );

END;
/


-- ERRO -20008
-- AUTOR NÃO INFORMADO
BEGIN

    pkg_biblioteca.cadastrar_livro(
        'Livro Teste',
        NULL,
        'Categoria Teste',
        10
    );

END;
/


-- ERRO -20004
-- LIVRO NÃO ENCONTRADO PARA ATUALIZAÇÃO
BEGIN

    pkg_biblioteca.atualizar_livro(
        999,
        'Livro Teste',
        'Autor Teste',
        'Categoria Teste',
        10
    );

END;
/


-- ERRO -20004
-- LIVRO NÃO ENCONTRADO PARA EXCLUSÃO
BEGIN

    pkg_biblioteca.excluir_livro(
        999
    );

END;
/


-- ERRO -20003
-- CPF NÃO CADASTRADO NA DEVOLUÇÃO
BEGIN

    pkg_biblioteca.registrar_devolucao(
        '99999999999',
        1
    );

END;
/


-- ERRO -20005
-- EMPRÉSTIMO NÃO ENCONTRADO
BEGIN

    pkg_biblioteca.registrar_devolucao(
        '12345678900',
        999
    );

END;
/


-- ERRO -20009
-- EMPRÉSTIMO JÁ DEVOLVIDO
-- EXECUTAR APÓS UMA DEVOLUÇÃO JÁ TER SIDO REGISTRADA
BEGIN

    pkg_biblioteca.registrar_devolucao(
        '12345678900',
        1
    );

END;
/